# Form implementation generated from reading ui file 'c:\Users\kusha\OneDrive\Desktop\RailTel-Projects\Test\appui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(879, 644)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("background-color:#FF9B9B;\n"
"")
        self.tool_name = QtWidgets.QLabel(parent=mainWindow)
        self.tool_name.setGeometry(QtCore.QRect(10, 10, 861, 21))
        self.tool_name.setStyleSheet("background-color:#A7EDE7;\n"
"border-style:outset;\n"
"border-radius:5px;")
        self.tool_name.setObjectName("tool_name")
        self.virustotal_btn = QtWidgets.QPushButton(parent=mainWindow)
        self.virustotal_btn.setGeometry(QtCore.QRect(10, 620, 191, 21))
        self.virustotal_btn.setStyleSheet("QPushButton{\n"
"    background-color:#91C8E4;\n"
"    color:black;\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"border-color:transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #DBC4F0;\n"
"    border-style:outset;\n"
"    border-color:#98EECC;\n"
"}\n"
"")
        self.virustotal_btn.setObjectName("virustotal_btn")
        self.networking_btn = QtWidgets.QPushButton(parent=mainWindow)
        self.networking_btn.setGeometry(QtCore.QRect(200, 620, 211, 21))
        self.networking_btn.setStyleSheet("QPushButton{\n"
"    background-color:#91C8E4;\n"
"    color:black;\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"border-color:transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #DBC4F0;\n"
"    border-style:outset;\n"
"    border-color:#98EECC;\n"
"}\n"
"")
        self.networking_btn.setObjectName("networking_btn")
        self.system_monitoring_btn = QtWidgets.QPushButton(parent=mainWindow)
        self.system_monitoring_btn.setGeometry(QtCore.QRect(410, 620, 221, 21))
        self.system_monitoring_btn.setStyleSheet("QPushButton{\n"
"    background-color:#91C8E4;\n"
"    color:black;\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"border-color:transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #DBC4F0;\n"
"    border-style:outset;\n"
"    border-color:#98EECC;\n"
"}\n"
"")
        self.system_monitoring_btn.setObjectName("system_monitoring_btn")
        self.submit_report_btn = QtWidgets.QPushButton(parent=mainWindow)
        self.submit_report_btn.setGeometry(QtCore.QRect(630, 620, 241, 21))
        self.submit_report_btn.setStyleSheet("QPushButton{\n"
"    background-color:#91C8E4;\n"
"    color:black;\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"border-color:transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #DBC4F0;\n"
"    border-style:outset;\n"
"    border-color:#98EECC;\n"
"}\n"
"")
        self.submit_report_btn.setObjectName("submit_report_btn")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=mainWindow)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 40, 861, 571))
        self.stackedWidget.setStyleSheet("background-color:#749BC2;\n"
"border-radius:10px;\n"
"border-color:black;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.virustotal = QtWidgets.QWidget()
        self.virustotal.setStyleSheet("border-radius:5px;")
        self.virustotal.setObjectName("virustotal")
        self.label_2 = QtWidgets.QLabel(parent=self.virustotal)
        self.label_2.setGeometry(QtCore.QRect(310, 0, 111, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.scan_virustotal_btn = QtWidgets.QPushButton(parent=self.virustotal)
        self.scan_virustotal_btn.setGeometry(QtCore.QRect(10, 510, 151, 41))
        self.scan_virustotal_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.scan_virustotal_btn.setObjectName("scan_virustotal_btn")
        self.stackedWidget.addWidget(self.virustotal)
        self.system_administration = QtWidgets.QWidget()
        self.system_administration.setStyleSheet("border-radius:5px;")
        self.system_administration.setObjectName("system_administration")
        self.label = QtWidgets.QLabel(parent=self.system_administration)
        self.label.setGeometry(QtCore.QRect(320, 0, 131, 31))
        self.label.setStyleSheet("border-color:#FAF0D7;\n"
"border-width:2px;")
        self.label.setObjectName("label")
        self.process_monitor_frame = QtWidgets.QFrame(parent=self.system_administration)
        self.process_monitor_frame.setGeometry(QtCore.QRect(10, 160, 241, 401))
        self.process_monitor_frame.setStyleSheet("QFrame {\n"
"                background-color: lightgreen;\n"
"                border-radius:5px;;\n"
"            }\n"
"QFrame:hover {\n"
"                background-color: #EBE645;\n"
"                 \n"
"            }")
        self.process_monitor_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.process_monitor_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.process_monitor_frame.setObjectName("process_monitor_frame")
        self.admin_processes_btn = QtWidgets.QPushButton(parent=self.process_monitor_frame)
        self.admin_processes_btn.setGeometry(QtCore.QRect(20, 40, 161, 41))
        self.admin_processes_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.admin_processes_btn.setObjectName("admin_processes_btn")
        self.programs_btn = QtWidgets.QPushButton(parent=self.process_monitor_frame)
        self.programs_btn.setGeometry(QtCore.QRect(20, 90, 161, 41))
        self.programs_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.programs_btn.setObjectName("programs_btn")
        self.scheduled_task_btn = QtWidgets.QPushButton(parent=self.process_monitor_frame)
        self.scheduled_task_btn.setGeometry(QtCore.QRect(20, 140, 161, 41))
        self.scheduled_task_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.scheduled_task_btn.setObjectName("scheduled_task_btn")
        self.start_at_boot_processes = QtWidgets.QPushButton(parent=self.process_monitor_frame)
        self.start_at_boot_processes.setGeometry(QtCore.QRect(20, 190, 161, 41))
        self.start_at_boot_processes.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.start_at_boot_processes.setObjectName("start_at_boot_processes")
        self.autoexec_btn = QtWidgets.QPushButton(parent=self.process_monitor_frame)
        self.autoexec_btn.setGeometry(QtCore.QRect(20, 240, 161, 41))
        self.autoexec_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.autoexec_btn.setObjectName("autoexec_btn")
        self.running_process_btn = QtWidgets.QPushButton(parent=self.process_monitor_frame)
        self.running_process_btn.setGeometry(QtCore.QRect(20, 290, 161, 41))
        self.running_process_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.running_process_btn.setObjectName("running_process_btn")
        self.processes_monitoring_label = QtWidgets.QLabel(parent=self.process_monitor_frame)
        self.processes_monitoring_label.setGeometry(QtCore.QRect(20, 10, 181, 20))
        self.processes_monitoring_label.setStyleSheet("background-color:transparent;")
        self.processes_monitoring_label.setObjectName("processes_monitoring_label")
        self.security_monitor_frame = QtWidgets.QFrame(parent=self.system_administration)
        self.security_monitor_frame.setGeometry(QtCore.QRect(280, 160, 251, 401))
        self.security_monitor_frame.setStyleSheet("QFrame {\n"
"                background-color: lightgreen;\n"
"                border-radius:5px;;\n"
"            }\n"
"QFrame:hover {\n"
"                background-color: #EBE645;\n"
"                 \n"
"            }")
        self.security_monitor_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.security_monitor_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.security_monitor_frame.setObjectName("security_monitor_frame")
        self.security_monitor_label = QtWidgets.QLabel(parent=self.security_monitor_frame)
        self.security_monitor_label.setGeometry(QtCore.QRect(60, 10, 101, 20))
        self.security_monitor_label.setStyleSheet("background-color:transparent;")
        self.security_monitor_label.setObjectName("security_monitor_label")
        self.run_mrt_btn = QtWidgets.QPushButton(parent=self.security_monitor_frame)
        self.run_mrt_btn.setGeometry(QtCore.QRect(20, 40, 161, 41))
        self.run_mrt_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.run_mrt_btn.setObjectName("run_mrt_btn")
        self.run_taskmanager_btn = QtWidgets.QPushButton(parent=self.security_monitor_frame)
        self.run_taskmanager_btn.setGeometry(QtCore.QRect(20, 90, 161, 41))
        self.run_taskmanager_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.run_taskmanager_btn.setObjectName("run_taskmanager_btn")
        self.file_monitor_frame = QtWidgets.QFrame(parent=self.system_administration)
        self.file_monitor_frame.setGeometry(QtCore.QRect(570, 160, 251, 401))
        self.file_monitor_frame.setStyleSheet("QFrame {\n"
"                background-color: lightgreen;\n"
"                border-radius:5px;;\n"
"            }\n"
"QFrame:hover {\n"
"                background-color: #EBE645;\n"
"                 \n"
"            }")
        self.file_monitor_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.file_monitor_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.file_monitor_frame.setObjectName("file_monitor_frame")
        self.file_monitor_label = QtWidgets.QLabel(parent=self.file_monitor_frame)
        self.file_monitor_label.setGeometry(QtCore.QRect(110, 10, 91, 20))
        self.file_monitor_label.setStyleSheet("background-color:transparent;")
        self.file_monitor_label.setObjectName("file_monitor_label")
        self.stackedWidget.addWidget(self.system_administration)
        self.networking = QtWidgets.QWidget()
        self.networking.setStyleSheet("border-radius:5px;")
        self.networking.setObjectName("networking")
        self.networking_label = QtWidgets.QLabel(parent=self.networking)
        self.networking_label.setGeometry(QtCore.QRect(350, 10, 81, 21))
        self.networking_label.setStyleSheet("color:green;")
        self.networking_label.setObjectName("networking_label")
        self.listening_processes_btn = QtWidgets.QPushButton(parent=self.networking)
        self.listening_processes_btn.setGeometry(QtCore.QRect(20, 70, 141, 41))
        self.listening_processes_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.listening_processes_btn.setObjectName("listening_processes_btn")
        self.dns_cache_btn = QtWidgets.QPushButton(parent=self.networking)
        self.dns_cache_btn.setGeometry(QtCore.QRect(20, 123, 141, 41))
        self.dns_cache_btn.setStyleSheet("QPushButton{\n"
"    background-color:#CCEEBC;\n"
"    color:black;\n"
"    border-radius: 5px;\n"
"    border-width:2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9B9B;\n"
"}\n"
"")
        self.dns_cache_btn.setObjectName("dns_cache_btn")
        self.stackedWidget.addWidget(self.networking)

        self.retranslateUi(mainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Dialog"))
        self.tool_name.setText(_translate("mainWindow", "                                                                         RailTel SOC End Point Security Assesment Application"))
        self.virustotal_btn.setText(_translate("mainWindow", "Virus Total"))
        self.networking_btn.setText(_translate("mainWindow", "Networking"))
        self.system_monitoring_btn.setText(_translate("mainWindow", "System"))
        self.submit_report_btn.setText(_translate("mainWindow", "Submit Report"))
        self.label_2.setText(_translate("mainWindow", "Virus Total"))
        self.scan_virustotal_btn.setText(_translate("mainWindow", "Virus Total Scan Response"))
        self.label.setText(_translate("mainWindow", "System Administration"))
        self.admin_processes_btn.setText(_translate("mainWindow", "Admin Token Processes"))
        self.programs_btn.setText(_translate("mainWindow", "Programs"))
        self.scheduled_task_btn.setText(_translate("mainWindow", "Scheduled Task"))
        self.start_at_boot_processes.setText(_translate("mainWindow", "Processes Start At Boot"))
        self.autoexec_btn.setText(_translate("mainWindow", "Automatically Executed Exe"))
        self.running_process_btn.setText(_translate("mainWindow", "Show All running Processes"))
        self.processes_monitoring_label.setText(_translate("mainWindow", "Processes Monitoring Space"))
        self.security_monitor_label.setText(_translate("mainWindow", "Security Monitor"))
        self.run_mrt_btn.setText(_translate("mainWindow", "MRT"))
        self.run_taskmanager_btn.setText(_translate("mainWindow", "Task Manager"))
        self.file_monitor_label.setText(_translate("mainWindow", "File Monitor"))
        self.networking_label.setText(_translate("mainWindow", "NETWORKING"))
        self.listening_processes_btn.setText(_translate("mainWindow", "Listening Processes"))
        self.dns_cache_btn.setText(_translate("mainWindow", "DNS Cache"))
